name: 'Terraform GitHub Actions'
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'Iac'
          tf_actions_comment: true
          tf_actions_cli_credentials_hostname: app.terraform.io 
          tf_actions_cli_credentials_token: ${{ secrets.TF_API_TOKEN }}
          #args: '-backend-config="token=${{ secrets.TF_API_TOKEN }}" -backend-config="organization=BEE-A-LEARNER"'
        env:
          #TF_WORKSPACE: dev
          GITHUB_TOKEN: 'ot-61Wyhfew8HejC5D1'
